import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { GeneratedPaperModel, type GeneratedPaperDocument } from "@/models/GeneratedPaper.model.js";
import { AppError } from "@/utils/AppError.js";

const pageWidth = 595.28;
const pageHeight = 841.89;
const margin = 54;

interface PdfRenderingContext {
  pdfDoc: PDFDocument;
  page: PDFPage;
  y: number;
}

// Prevents standard PDF fonts from throwing "WinAnsiEncoding cannot encode character" on AI smart quotes & math symbols
function sanitizeTextForPdf(text: string | number | undefined | null): string {
  if (text === undefined || text === null) return "";
  const str = String(text);
  return str
    .replace(/[\u201c\u201d]/g, '"') // smart double quotes
    .replace(/[\u2018\u2019]/g, "'") // smart single quotes
    .replace(/[\u2013\u2014]/g, "-") // en-dash and em-dash
    .replace(/\u2212/g, "-")         // minus sign
    .replace(/\u00b0/g, " degrees ") // degree symbol
    .replace(/[\u2026]/g, "...")     // ellipsis
    .replace(/[^\x00-\x7F\u00A0-\u00FF]/g, "?"); // replace any non-WinAnsi character with ?
}

export async function generatePdfForPaper(paper: GeneratedPaperDocument) {
  const pdfDoc = await PDFDocument.create();
  const regular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  
  const ctx: PdfRenderingContext = {
    pdfDoc,
    page: pdfDoc.addPage([pageWidth, pageHeight]),
    y: pageHeight - margin
  };

  const ensureSpace = (space: number) => {
    if (ctx.y < margin + space) {
      ctx.page = ctx.pdfDoc.addPage([pageWidth, pageHeight]);
      ctx.y = pageHeight - margin;
    }
  };

  ctx.page.drawText(sanitizeTextForPdf(paper.schoolName), { x: margin, y: ctx.y, size: 17, font: bold, color: rgb(0.08, 0.08, 0.08) });
  ctx.y -= 28;
  ctx.page.drawText(sanitizeTextForPdf(`Subject: ${paper.subject}`), { x: margin, y: ctx.y, size: 11, font: regular });
  ctx.page.drawText(sanitizeTextForPdf(`Class: ${paper.grade}`), { x: margin + 170, y: ctx.y, size: 11, font: regular });
  ctx.page.drawText(sanitizeTextForPdf(`Maximum Marks: ${paper.maximumMarks}`), { x: margin + 340, y: ctx.y, size: 11, font: regular });
  ctx.y -= 26;
  ctx.page.drawText(sanitizeTextForPdf(`Time Allowed: ${paper.timeAllowed}`), { x: margin, y: ctx.y, size: 11, font: regular });
  ctx.y -= 32;
  ctx.page.drawText("Name: __________________________", { x: margin, y: ctx.y, size: 10, font: regular });
  ctx.page.drawText("Roll Number: ______________", { x: margin + 255, y: ctx.y, size: 10, font: regular });
  ctx.y -= 18;
  ctx.page.drawText("Class/Section: ______________", { x: margin, y: ctx.y, size: 10, font: regular });
  ctx.y -= 30;

  paper.sections.forEach((section) => {
    ensureSpace(90);
    ctx.page.drawText(sanitizeTextForPdf(section.name), { x: margin, y: ctx.y, size: 13, font: bold });
    ctx.y -= 19;
    drawWrappedText(ctx, section.instruction, margin, pageWidth - margin * 2, 9, regular, 3);
    ctx.y -= 6;

    section.questions.forEach((question, index) => {
      ensureSpace(70);
      const diffLabel = question.difficulty ? `[${question.difficulty.toUpperCase()}] ` : "";
      const questionText = `${index + 1}. ${diffLabel}${question.question} [${question.marks} Marks]`;
      drawWrappedText(
        ctx,
        questionText,
        margin,
        pageWidth - margin * 2,
        10,
        regular,
        4
      );
      ctx.y -= 4;

      if (question.options?.length) {
        drawWrappedText(
          ctx,
          `Options: ${question.options.join(" | ")}`,
          margin + 16,
          pageWidth - margin * 2 - 16,
          9,
          regular,
          3
        );
        ctx.y -= 4;
      }
    });

    ctx.y -= 10;
  });

  ensureSpace(110);
  ctx.page.drawText("Answer Key", { x: margin, y: ctx.y, size: 13, font: bold });
  ctx.y -= 18;
  paper.answerKey.forEach((answer) => {
    ensureSpace(34);
    drawWrappedText(ctx, answer, margin, pageWidth - margin * 2, 9, regular, 3);
    ctx.y -= 2;
  });

  // Global Footer & Page Numbering across all generated pages
  const pages = pdfDoc.getPages();
  pages.forEach((p, index) => {
    // Horizontal divider
    p.drawLine({
      start: { x: margin, y: margin - 10 },
      end: { x: pageWidth - margin, y: margin - 10 },
      thickness: 0.5,
      color: rgb(0.9, 0.9, 0.9)
    });
    
    // Left side notice
    p.drawText("Generated by VedaAI Assessment Creator", {
      x: margin,
      y: margin - 22,
      size: 7.5,
      font: regular,
      color: rgb(0.5, 0.5, 0.5)
    });

    // Right side page number
    p.drawText(`Page ${index + 1} of ${pages.length}`, {
      x: pageWidth - margin - 50,
      y: margin - 22,
      size: 7.5,
      font: regular,
      color: rgb(0.5, 0.5, 0.5)
    });
  });

  return Buffer.from(await pdfDoc.save());
}

export async function savePdfToPaper(paperId: string) {
  const paper = await GeneratedPaperModel.findById(paperId);
  if (!paper) {
    throw new AppError("Generated paper not found", 404, "PAPER_NOT_FOUND");
  }

  const pdfBuffer = await generatePdfForPaper(paper);
  const pdfFileName = `${paper.title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-question-paper.pdf`;

  paper.pdfBuffer = pdfBuffer;
  paper.pdfFileName = pdfFileName;
  await paper.save();

  return paper;
}

function drawWrappedText(
  ctx: PdfRenderingContext,
  text: string,
  x: number,
  maxWidth: number,
  size: number,
  font: PDFFont,
  lineGap = 5
) {
  const sanitizedText = sanitizeTextForPdf(text);
  const words = sanitizedText.split(" ");
  const lines: string[] = [];
  let current = "";

  words.forEach((word) => {
    const test = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(test, size) > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = test;
    }
  });

  if (current) lines.push(current);

  lines.forEach((line) => {
    const lineHeight = size + lineGap;
    if (ctx.y < margin + lineHeight) {
      ctx.page = ctx.pdfDoc.addPage([pageWidth, pageHeight]);
      ctx.y = pageHeight - margin;
    }

    ctx.page.drawText(line, {
      x,
      y: ctx.y,
      size,
      font,
      color: rgb(0.1, 0.1, 0.1)
    });

    ctx.y -= lineHeight;
  });
}

